variable "project_id" {
  description = "Scaleway Project ID"
  type        = string
}

variable "scw_access_key" {
  description = "Scaleway Access Key (same as used for Terraform provider)"
  type        = string
  sensitive   = true
}

variable "scw_secret_key" {
  description = "Scaleway Secret Key (same as used for Terraform provider)"
  type        = string
  sensitive   = true
}

variable "region" {
  description = "Scaleway Region"
  type        = string
  default     = "fr-par"
}

variable "zone" {
  description = "Scaleway Zone"
  type        = string
  default     = "fr-par-1"
}

variable "env" {
  description = "Environment name (e.g. prod, staging)"
  type        = string
  default     = "prod"
}

variable "secret_key" {
  description = "Secret key for JWT token signing and application security. Database credentials are auto-generated by Scaleway."
  type        = string
  sensitive   = true
}

variable "custom_domain" {
  description = "Custom domain for the frontend (e.g. gift-genie.eu)"
  type        = string
  default     = null
}

variable "redis_password" {
  description = "DEPRECATED: No longer used. Kept for backward compatibility during migration."
  type        = string
  sensitive   = true
  default     = ""
}

variable "default_username" {
  description = "Default username for managed services (Redis, databases, etc.)"
  type        = string
  default     = "gift_genie"
}

variable "ovh_application_key" {
  description = "OVH API application key"
  type        = string
  sensitive   = true
}

variable "ovh_application_secret" {
  description = "OVH API application secret"
  type        = string
  sensitive   = true
}

variable "ovh_consumer_key" {
  description = "OVH API consumer key"
  type        = string
  sensitive   = true
}

variable "ovh_zone_name" {
  description = "OVH DNS zone name (e.g., gift-genie.eu)"
  type        = string
  default     = "gift-genie.eu"
}

variable "backend_image_tag" {
  description = "Docker image tag for backend (typically git commit SHA)"
  type        = string
  default     = "latest"
}

  description = "Docker image tag for frontend (typically git commit SHA)"
  type        = string
  default     = "latest"
}

variable "db_iam_principal_id" {
  description = "IAM Principal ID (User or Application UUID) for database authentication"
  type        = string
}
