from datetime import timedelta
from typing import Protocol


class PasswordHasher(Protocol):
    async def hash(self, password: str) -> str: ...
    async def verify(self, password: str, password_hash: str) -> bool: ...


class JWTService(Protocol):
    def create_access_token(self, data: dict, expires_delta: timedelta | None = None) -> str: ...
    def verify_token(self, token: str) -> dict | None: ...
