"""Add role column to users table

Revision ID: 14beb18878a9
Revises: ffbd152c3c69
Create Date: 2025-12-16 13:59:24.703888

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '14beb18878a9'
down_revision: str | None = 'ffbd152c3c69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum('ADMIN', 'USER', name='userrole')
    user_role.create(op.get_bind())
    op.add_column('users', sa.Column('role', user_role, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
