"""add permissions and user_permissions tables

Revision ID: 19f057918b6f
Revises: 14beb18878a9
Create Date: 2025-12-16 17:03:38.664935

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "19f057918b6f"
down_revision: str | None = "14beb18878a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index("idx_permissions_category", "permissions", ["category"], unique=False)
    op.create_index("idx_permissions_code", "permissions", ["code"], unique=False)
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["permission_code"], ["permissions.code"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "permission_code"),
    )
    op.create_index(
        "idx_user_permissions_permission_code",
        "user_permissions",
        ["permission_code"],
        unique=False,
    )
    op.create_index("idx_user_permissions_user_id", "user_permissions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_permissions_user_id", table_name="user_permissions")
    op.drop_index("idx_user_permissions_permission_code", table_name="user_permissions")
    op.drop_table("user_permissions")
    op.drop_index("idx_permissions_code", table_name="permissions")
    op.drop_index("idx_permissions_category", table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
