"""add member language

Revision ID: cbf6d2bc313d
Revises: 1a2b3c4d5e6f
Create Date: 2025-12-28 16:55:01.678508

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "cbf6d2bc313d"
down_revision: str | None = "1a2b3c4d5e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("language", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "language")
    # ### end Alembic commands ###
